t = (open("data/text0.txt", "r", encoding="utf-8")).read()

print(t)

text0 = (open("data/text0.txt", "r", encoding="utf-8")).read()
text1_1_1 = (open("data/text1.1.1.txt", "r", encoding="utf-8")).read()
text1_1_2 = (open("data/text1.1.2.txt", "r", encoding="utf-8")).read()
text1_1_3 = (open("data/text1.1.3.txt", "r", encoding="utf-8")).read()
text1_1_4_1 = (open("data/text1.1.4.1.txt", "r", encoding="utf-8")).read()
text1_1_4_2 = (open("data/text1.1.4.3.txt", "r", encoding="utf-8")).read()
text1_1_4_3 = (open("data/text1.1.4.3.txt", "r", encoding="utf-8")).read()
text1_1_4 = (open("data/text1.1.4.txt", "r", encoding="utf-8")).read()
text1_1_5_1 = (open("data/text1.1.5.1.txt", "r", encoding="utf-8")).read()
text1_1_5_2 = (open("data/text1.1.5.2.txt", "r", encoding="utf-8")).read()
text1_1_5 = (open("data/text1.1.5.txt", "r", encoding="utf-8")).read()
text1_1_6 = (open("data/text1.1.6.txt", "r", encoding="utf-8")).read()
text1_1_7 = (open("data/text1.1.7.txt", "r", encoding="utf-8")).read()
text1_2_1 = (open("data/text1.2.1.txt", "r", encoding="utf-8")).read()
text1_2_2 = (open("data/text1.2.2.txt", "r", encoding="utf-8")).read()
text1_2_3 = (open("data/text1.2.3.txt", "r", encoding="utf-8")).read()
text1_2_4 = (open("data/text1.2.4.txt", "r", encoding="utf-8")).read()
text1_2_5 = (open("data/text1.2.5.txt", "r", encoding="utf-8")).read()
text1_2_6 = (open("data/text1.2.6.txt", "r", encoding="utf-8")).read()
text1_3_1 = (open("data/text1.3.1.txt", "r", encoding="utf-8")).read()
text1_3_2 = (open("data/text1.3.2.txt", "r", encoding="utf-8")).read()
text1_3_3 = (open("data/text1.3.3.txt", "r", encoding="utf-8")).read()
text1_3_4 = (open("data/text1.3.4.txt", "r", encoding="utf-8")).read()
text1_3_5 = (open("data/text1.3.5.txt", "r", encoding="utf-8")).read()
text2_1 = (open("data/text2.1.txt", "r", encoding="utf-8")).read()
text2_2 = (open("data/text2.2.txt", "r", encoding="utf-8")).read()
text2_3 = (open("data/text2.3.txt", "r", encoding="utf-8")).read()
text2 = (open("data/text2.txt", "r", encoding="utf-8")).read()
text3 = (open("data/text3.txt", "r", encoding="utf-8")).read()
text4 = (open("data/text4.txt", "r", encoding="utf-8")).read()
text5 = (open("data/text5.txt", "r", encoding="utf-8")).read()
text6 = (open("data/text6.txt", "r", encoding="utf-8")).read()
text7 = (open("data/text7.txt", "r", encoding="utf-8")).read()
text8 = (open("data/text8.txt", "r", encoding="utf-8")).read()
